version: '3.9'

services:
  authserver:
    image: pandaria:authserver
    container_name: pandaria-authserver
    build:
      context: authserver
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    environment:
      - TZ=Europe/Stockholm
    ports:
      - "3724:3724"
    volumes:
      - "./server:/opt/server:rw"
    restart: on-failure
    tty: true

  compile:
    image: pandaria:compile
    env_file:
      - ./compile/compile.env
    container_name: pandaria-compile
    hostname: compile
    build:
      context: compile
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    environment:
      - TZ=Europe/Stockholm
    volumes:
      - ./server:/opt/server:rw
      - ./etc:/opt/etc:rw
      - ${WOW_PATH}:/opt/wow:rw
    restart: on-failure
    tty: true

  mysql:
    image: pandoria:mysql
      #env_file:
      # - ./mariadb/mariadb.env
    container_name: pandoria-mysql
    hostname: pandaradb
    build:
      context: mysql
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
    # ports:
    #  - "3306:3306"
    volumes:
      - ./server:/opt/server:rw
      - ./etc:/opt/etc:rw
    restart: on-failure
    tty: true

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=trinitydb
      - PMA_USER=root
      - PMA_PASSWORD=pwd
    restart: "no"
    depends_on:
      - compile
    profiles:
      - dev
  
  worldserver:
    image: pandaria:worldserver
    container_name: pandaria-worldserver
    build:
      context: worldserver
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    environment:
      - TZ=Europe/Stockholm
    ports:
      - "3443:3443"
      - "8085:8085"
    # - "8086:8086"
    volumes:
      - "./server:/opt/server:rw"
    restart: on-failure
    tty: true
networks:
  default:
    name: pandaria-network
